### ISSUE TITLE
Is there a way...

### ISSUE THREAD

**Issue by benjaminedwardswebdesign** [gsvineeth/rwdgrid#4]
Hi there, 

I currently use Skeleton framework but need more width for my design.  When coding html / css is there a way to offset?

For example I need a box on the right but nothing on the left. How would I do that?

Cheers,

Ben.

**Comment by cmwwebfx** [comment]
+ 1 on this question
A year old question with no reply makes me wonder if this is maintained though.

**Comment by gsvineeth** [comment]
@cmwwebfx 
Hey Ciaran, sorry for the late response. I was off from this last year and did a major rework from scratch on this framework two months back. 

@benjaminedwardswebdesign  Currently It doesnt support offset, as whole idea of this framework is light weight and performance oriented, I shall work on a Fat version as well, with lot of helper classes and offset.
